export const LOG_IN = 'LOG_IN'
export const LOG_OUT = 'LOG_OUT'

export const UPDATE_USERINFO = 'UPDATE_USERINFO'

export const SHOW_POPUPFORM = 'SHOW_POPUPFORM'
export const HIDE_POPUPFORM = 'HIDE_POPUPFORM'

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION'
// export const DELETE_NOTIFICATION = ''

export const UPDATE_CHALLENGES = 'UPDATE_CHALLENGES'
export const UPDATE_RANKS = 'UPDATE_RANKS'
export const UPDATE_ANNOUNCEMENTS = 'UPDATE_ANNOUNCEMENTS'

export const SLOVE_CHALLENGE = 'SLOVE_CHALLENGE'
